name: CI

on:
  push:
    branches:
      - main

jobs:

  ci-main:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v2
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

      - name: Tag build
        # Based on https://axion-release-plugin.readthedocs.io/en/latest/configuration/ci_servers/#github-actions
        run: ./gradlew release -Prelease.customUsername=${{ github.actor }} -Prelease.customPassword=${{ github.token }}

      - name: Build
        run: |
          ./gradlew build

      - name: Get version
        id: get_version
        run: |
          version=$(./gradlew currentVersion -q -Prelease.quiet)
          echo "Version: $version"
          echo ::set-output name=VERSION::$version

      - name: Publish JARs to Maven Central
        run: ./gradlew --no-parallel publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
